/*
 * This source file was generated by the Gradle 'init' task
 */

package employee_manager;
import employee_manager.util.Constants;


import java.io.IOException;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;


public class App extends Application{
    @Override
    public void start(Stage stage){
        try{
            FXMLLoader loader = new FXMLLoader(getClass().getResource(Constants.LOGIN_VIEW));
            Parent root = loader.load();

            Scene scene = new Scene(root, Constants.SCREEN_WIDTH, Constants.SCREEN_HEIGHT);
            stage.setScene(scene);
            stage.setTitle("Employee Manager App");
            stage.show();
        }
        catch (IOException e){
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
       launch();
    }
}
